export const inputActionTypes = {
  SET_CURRENT_EMAIL: 'SET_CURRENT_EMAIL',
  SET_CURRENT_PASSWORD: 'SET_CURRENT_PASSWORD',
  CLEAN_CURRENT_STATE: 'CLEAN_CURRENT_STATE',
};

export const validationActionTypes = {
  SET_EMAIL_VALIDATION: 'SET_EMAIL_VALIDATION',
  SET_PASSWORD_VALIDATION: 'SET_PASSWORD_VALIDATION',
  CLEAN_VALIDATION_STATE: 'CLEAN_VALIDATION_STATE',
};

export const loginActionTypes = {
  SET_LOGIN_EMAIL: 'SET_LOGIN_EMAIL',
  SET_LOGIN_PASSWORD: 'SET_LOGIN_PASSWORD',
};
