export const inputActionTypes = {
  SET_CURRENT_EMAIL: ' SET_CURRENT_EMAIL',
  SET_CURRENT_PASSWORD: 'SET_CURRENT_PASSWORD',
};

export const validationActionTypes = {
  SET_EMAIL_VALIDATION: 'SET_EMAIL_VALIDATION',
  SET_PASSWORD_VALIDATION: 'SET_PASSWORD_VALIDATION',
};

export const loginActionTypes = {
  SET_LOGIN_EMAIL: 'SET_LOGIN_EMAIL',
  SET_LOGIN_PASSWORD: 'SET_LOGIN_PASSWORD',
};
